#!/bin/sh

if [ -f /var/log/nginx/access.status-log ]; then
  mv /var/log/nginx/access.status-log /var/log/nginx/access.status-log.old
fi

if [ -f /var/run/nginx.pid ]; then
  kill -USR1 $(cat /var/run/nginx.pid)
fi