#!/usr/bin/env bash

generate_nginx_config(){
  local domain="${1}"
  certs_root_path="/etc/letsencrypt/live/${domain}"
  changes="-e 's|listen 80.*|listen 80;|g'"
  changes="${changes} -e '/# Generated by Keitaro/d'"
  changes="${changes} -e '1i# Generated by Keitaro ${SCRIPT_NAME} v${RELEASE_VERSION}'"
  changes="${changes} -e 's|server_name .*|server_name ${domain};|g'"
  changes="${changes} -e 's|ssl_certificate .*|ssl_certificate ${certs_root_path}/fullchain.pem;|g'"
  changes="${changes} -e 's|ssl_certificate_key .*|ssl_certificate_key ${certs_root_path}/privkey.pem;|g'"
  command="cat ${NGINX_KEITARO_CONF} | sed ${changes} > ${NGINX_VHOSTS_DIR}/${domain}.conf"
  generating_message=$(translate "messages.generating_nginx_config_for")
  run_command "${command}" "${generating_message} ${domain}" "hide_output"
}
