#!/usr/bin/env bash

generate_nginx_host_config(){
  local domain="${1}"
  local certs_root_path="/etc/letsencrypt/live/${domain}"
  local vhost_path="${NGINX_VHOSTS_DIR}/${domain}.conf"
  local changes="-e 's|listen 80.*|listen 80;|g'"
  changes="${changes} -e 's|server_name .*|server_name ${domain};|g'"
  changes="${changes} -e 's|ssl_certificate .*|ssl_certificate ${certs_root_path}/fullchain.pem;|g'"
  changes="${changes} -e 's|ssl_certificate_key .*|ssl_certificate_key ${certs_root_path}/privkey.pem;|g'"
  local command="sed -i ${changes} ${vhost_path}"
  if [[ is_exists_file "${vhost_path}" && grep -q -P '^# Generated by Keitaro .* v${RELEASE_VERSION}' "${vhost_path}" ]]; then
    command="cp ${NGINX_KEITARO_CONF} ${vhost_path} && ${command}"
  fi
  generating_message=$(translate "messages.generating_nginx_config_for")
  run_command "${command}" "${generating_message} ${domain}" "hide_output"
}
