FROM centos:{{ centos_major_version }}

RUN yum install -y deltarpm epel-release \
    && rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-{{ centos_major_version }}.rpm \
    && yum update -y

RUN yum install -y --enablerepo=remi {{ php_version }} \
                                     {{ php_version }}-php-devel \
                                     {{ php_version }}-php-mysqlnd \
                                     {{ php_version }}-php-pecl-redis \
                                     {{ php_version }}-php-mbstring \
                                     {{ php_version }}-php-pear \
                                     {{ php_version }}-php-xml

RUN if [[ "{{ php_version }}" =~ ^php5 ]]; then \
      yum install -y --enablerepo=remi {{ php_version }}-php-ioncube-loader; \
    fi

RUN ln -s /usr/bin/{{ php_version }} /usr/bin/php \
    && ln -s /opt/remi/{{ php_version }}/root/bin/php-config /usr/bin/php-config

RUN if [[ "{{ php_version }}" =~ ^php5 ]]; then \
      ln -s /opt/remi/{{ php_version }}/root/etc/ /etc/php; \
    else \
      ln -s /etc/opt/remi/{{ php_version }} /etc/php; \
    fi

RUN sed -i -e 's/^;?memory_limit = .*/memory_limit={{ php_memory_limit }}/' \
           -e 's|^;?date.timezone =.*|date.timezone = "{{ timezone }}"|' \
           /etc/php/php.ini

ENTRYPOINT ["/usr/bin/php"]
