FROM centos:{{ centos_major_version }}

RUN yum install -y deltarpm epel-release \
    && rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-{{ centos_major_version }}.rpm \
    && yum update -y

RUN yum install -y --enablerepo=remi {{ image_version }} \
                                     {{ image_version }}-php-devel \
                                     {{ image_version }}-php-mysqlnd \
                                     {{ image_version }}-php-pecl-redis \
                                     {{ image_version }}-php-mbstring \
                                     {{ image_version }}-php-pear \
                                     {{ image_version }}-php-xml \
                                     {{ image_version }}-php-ioncube-loader

RUN if [[ "{{ image_version }}" =~ ^php7 ]]; then \
      yum install -y --enablerepo=remi {{ image_version }}-php-pecl-zip; \
    fi

RUN ln -s /usr/bin/{{ image_version }} /usr/bin/php \
    && ln -s /opt/remi/{{ image_version }}/root/bin/php-config /usr/bin/php-config

RUN if [[ "{{ image_version }}" =~ ^php5 ]]; then \
      ln -s /opt/remi/{{ image_version }}/root/etc/ /etc/php; \
    else \
      ln -s /etc/opt/remi/{{ image_version }} /etc/php; \
    fi

RUN sed -i -r -e 's/^;?memory_limit = .*/memory_limit={{ php_memory_limit }}/' \
              -e 's|^;?date.timezone =.*|date.timezone = "{{ timezone }}"|' \
              /etc/php/php.ini

VOLUME ["/data", "/cache"]
WORKDIR /data

ENTRYPOINT ["/usr/bin/php"]
