FROM keitarotds/php:{{ php_version }}

ENV COMPOSER_CACHE_DIR=/cache

RUN yum install -y git

RUN curl https://getcomposer.org/installer -o composer-installer.php \
    && php composer-installer.php \
    && rm composer-installer.php \
    && chmod a+x composer.phar \
    && mv composer.phar /usr/local/bin/composer
    
ENTRYPOINT ["/usr/local/bin/composer"]
