FROM {{ item.image }}
ENV container=docker

# Install systemd -- See https://hub.docker.com/_/centos/
RUN \
  (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
  rm -f /lib/systemd/system/multi-user.target.wants/*;\
  rm -f /etc/systemd/system/*.wants/*;\
  rm -f /lib/systemd/system/local-fs.target.wants/*; \
  rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
  rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
  rm -f /lib/systemd/system/basic.target.wants/*;\
  rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum -y update

RUN yum -y install epel-release \
                   https://rpms.remirepo.net/enterprise/remi-release-7.rpm

RUN yum -y install ansible \
                   cronie \
                   initscripts \
                   jemalloc \
                   lsof \
                   openssl \
                   php74 \
                   php74-php-fpm \
                   php74-php-ioncube-loader \
                   python3-libselinux \
                   rsync \
                   selinux-policy-targeted \
                   socat \
                   strace \
                   sudo \
                   unzip

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]
