#!/usr/bin/env bash
#





assert_server_configuration_relevant(){
  debug 'Ensure configs has been genereated by relevant installer'
  if isset "$SKIP_CHECKS"; then
    debug "SKIP: аctual check of installer version in ${INVENTORY_FILE} disabled"
  else
    if is_exists_file ${INVENTORY_FILE} && grep -q "^installer_version=${SCRIPT_VERSION}\$" ${INVENTORY_FILE}; then
      debug "Configs has been generated by recent version of installer ${SCRIPT_VERSION}"
    else
      fail "$(translate 'errors.reconfigure_keitaro')"
    fi
  fi
}
