#!/usr/bin/env bash
#





generate_vhost(){
  local domain="${1}"
  local message_key="${2}"
  debug "Generate vhost by ${TOOL_NAME} for domain "$domain""
  shift 2
  local generating_message="$(translate "${message_key}")"
  local command=''
  local changes=''
  local vhost_path="$(get_vhost_path "$domain")"
  local vhost_override_path="$(get_vhost_override_path "$domain")"
  local vhost_backup_path="$(get_vhost_backup_path "$domain")"
  if nginx_vhost_relevant "$vhost_path" && nginx_vhost_already_processed "$vhost_path"; then
    print_with_color "$(translate 'messages.skip_nginx_conf_generation')" "yellow"
    return
  else
    if is_file_exist "$vhost_path" no; then
      debug "Backing up nginx config for ${domain} to ${vhost_backup_path}"
      command="${command} cp ${vhost_path} ${vhost_backup_path} &&"
    fi
    command="${command} cp ${NGINX_KEITARO_CONF} ${vhost_path} &&"
  fi
  command="${command} touch ${vhost_override_path} &&"
  command="${command} sed -i $(nginx_vhost_sed_expressions "${@}") ${vhost_path}"
  run_command "${command}" "${generating_message} ${domain}" "hide_output"
}


get_vhost_override_path(){
  local domain="${1}"
  echo "${NGINX_VHOSTS_DIR}/local/${domain}.inc"
}


get_vhost_path(){
  local domain="${1}"
  echo "${NGINX_VHOSTS_DIR}/${domain}.conf"
}


get_vhost_backup_path(){
  local domain="${1}"
  echo "${NGINX_VHOSTS_DIR}/${domain}.conf.$(date +%Y%m%d%H%M%S)"
}


nginx_vhost_sed_expressions(){
  expressions="${expressions} -e '1a# Post-processed by Keitaro ${TOOL_NAME} tool v${RELEASE_VERSION}'"
  expressions="${expressions} -e '/server.inc;/a\ \ include ${vhost_override_path};'"
  expressions="${expressions} -e 's/listen 80 default_server/listen 80/'"
  expressions="${expressions} -e 's/server_name _/server_name ${domain}/'"
  while isset "${1}"; do
    expressions="${expressions} -e '${1}'"
    shift
  done
  echo "$expressions"
}


nginx_vhost_relevant(){
  local vhost_path="${1}"
  test -f "$vhost_path" && grep -q "# Generated by Keitaro install tool v${RELEASE_VERSION}" "$vhost_path"
}


nginx_vhost_already_processed(){
  local vhost_path="${1}"
  test -f "$vhost_path" && grep -q "# Post-processed by Keitaro ${TOOL_NAME} tool v${RELEASE_VERSION}" "$vhost_path"
}
