#!/usr/bin/env bash
#






regenerate_nginx_host_config(){
  local domain="${1}"
  local message_key="${2}"
  local generating_message="$(translate "${message_key}")"
  local command=""
  local changes=""
  if is_nginx_config_exist "$domain"; then
    command="${command}cp $(vhost_path "$domain") $(vhost_backup_path "$domain") && "
  fi
  if need_to_regenerate_host_config $(vhost_path "$domain"); then
    command="${command}cp ${NGINX_KEITARO_CONF} $(vhost_path "$domain") && "
    changes="${changes}$(build_sed_expression_from_nginx_setting_block 'listen: listen 80')"
    changes="${changes}$(build_sed_expression_from_nginx_setting_block 'server_name ${domain}')"
  fi
  while isset "${3}"; do
    changes="${changes}$(build_sed_expression_from_nginx_setting_block "${3}")"
    shift
  done
  command="${command}sed -i ${changes} ${vhost_path}"
  run_command "${command}" "${generating_message} ${domain}" "hide_output"
}


need_to_regenerate_host_config(){
  local vhost_path="${1}"
  ! is_nginx_config_exist "$vhost_path" || ! vhost_config_relevant "$vhost_path"
}


is_nginx_config_exist(){
  local domain="${1}"
  is_file_exist "$(vhost_path "$domain")" no
}


vhost_config_relevant(){
  local vhost_path="${1}"
  grep -q -P "^# Generated by Keitaro .* v${RELEASE_VERSION}" "${vhost_path}"
}


vhost_path(){
  local domain="${1}"
  echo "${NGINX_VHOSTS_DIR}/${domain}.conf"
}

vhost_backup_path(){
  local domain="${1}"
  echo "${NGINX_VHOSTS_DIR}/${domain}.conf.$(date +%Y%m%d%H%M%s)"
}


build_sed_expression_from_nginx_setting_block(){
  local setting_block="${1}"
  IFS=":" read block setting <<< "$setting_block"
  if empty "$setting"; then
    setting=$block
    block=""
  fi
  read name value <<< "$setting"
  bounds=""
  if isset "$block"; then
    bounds='/# begin ${block}/,/# end ${block}/'
  fi
  echo "-e '${bounds}s|${name} .*|${name} ${value};|g'"
}
