source 'https://rubygems.org'

gem 'activesupport'

gem 'rspec-core',         '~> 3.5.0'
gem 'rspec-expectations', '~> 3.5.0'
gem 'rspec-mocks',        '~> 3.5.0'
gem 'byebug'
gem 'knapsack_pro'
gem 'rake'
